device: "cpu"
seed: 10

num_qubits: 8
num_iters: 201
num_envs: 32
steps: 8
steps_limit: 10
epsi: 1e-3
obs_fn: "rdm_2q_mean_real"
fast_obs: True
reward_fn: "relative_delta"
stategen_fn: "sample_haar_product"
stategen_params: [["min_subsystem_size", 1], ["max_subsystem_size", 2]]

pi_lr: 2e-4
vf_lr: 3e-4
discount: 1.0
batch_size: 128
clip_grad: 1.0
entropy_reg: 0.1
embed_dim: 64
dim_mlp: 256
attn_heads: 2
transformer_layers: 2

log_every: 5
checkpoint_every: 50
test_every: 100000
num_tests: 100
trigger_every: 20
triggers: ["StagedTrainingTrigger"]
triggers_levels: [
  [
    "StagedTrainingTrigger",
    [
      {
        test_max_steps: 10,
        test_min_subsystem_size: 2,
        test_max_subsystem_size: 2,
        threshold_average_length: 5.0,
        threshold_ratio_terminated: 0.98,
        env_parameters: { max_episode_steps: 10 },
        sgen_parameters: { min_subsystem_size: 1, max_subsystem_size: 3},
        agent_parameters: {}
      },

      {
        test_max_steps: 10,
        test_min_subsystem_size: 3,
        test_max_subsystem_size: 3,
        threshold_average_length: 7.0,
        threshold_ratio_terminated: 0.98,
        env_parameters: { max_episode_steps: 10 },
        sgen_parameters: { min_subsystem_size: 1, max_subsystem_size: 4},
        agent_parameters: {}
      },

      {
        test_max_steps: 15,
        test_min_subsystem_size: 4,
        test_max_subsystem_size: 4,
        threshold_average_length: 11.0,
        threshold_ratio_terminated: 0.98,
        env_parameters: { max_episode_steps: 10 },
        sgen_parameters: { min_subsystem_size: 2, max_subsystem_size: 4},
        agent_parameters: {}
      },

      {
        test_max_steps: 15,
        test_min_subsystem_size: 4,
        test_max_subsystem_size: 4,
        threshold_average_length: 11.0,
        threshold_ratio_terminated: 0.98,
        env_parameters: { max_episode_steps: 10 },
        sgen_parameters: { min_subsystem_size: 3, max_subsystem_size: 4},
        agent_parameters: {}
      }
    ]
  ]
]
logdir_prefix: "test_"
logdir_suffix: "_fast_obs"
