attn_heads: 4
batch_size: 512
checkpoint:
  filepath: logs/stage1_12q_1000iters_XL_product_v2.1/checkpoint1000.pickle
  use_iteration: true
  use_policy_fn: true
  use_policy_optim: true
  use_tracker: false
  use_triggers: false
  use_value_fn: true
  use_value_optim: true
checkpoint_every: 500
clip_grad: 1.0
dim_mlp: 1024
discount: 0.99
embed_dim: 256
entropy_reg: 0.001
env_device: cuda
epsi: 0.001
fast_ents: true
fast_obs: true
greedy_evaluation_policy: true
log_every: 100
logdir_prefix: stage2_
logdir_suffix: _XL_eta4.1_v2.1
logging: true
model_device: cuda
num_envs: 64
num_iters: 20000
num_ppo_updates: 96
num_qubits: 12
num_tests: 20
obs_fn: rdm2m
pi_freeze_iters: 0
pi_lr: 1.0e-05
pi_lr_gamma: null
pi_lr_milestones: null
reset_optimizers: false
reset_tracker: false
reward_fn: relative_delta
seed: 22
stategen_fn: sample_haar_generalized
stategen_params:
- - min_subsystem_size
  - 2
- - max_subsystem_size
  - 4
- - min_eta
  - 4.1
- - max_eta
  - 4.1
steps: 60
steps_limit: 100
test_every: 500
test_max_subsystem_size: 4
test_min_subsystem_size: 2
test_states: []
transformer_layers: 8
trigger_every: 100000
triggers: []
triggers_levels: []
vf_freeze_iters: 0
vf_lr: 1.0e-05
vf_lr_gamma: null
vf_lr_milestones: null
vf_warmup_iters: 0
